#############################################################################
# Makefile for building: qct08
# Generated by qmake (2.01a) (Qt 4.8.6) on: ? 12? 14 15:39:43 2014
# Project:  qct08.pro
# Template: app
# Command: /usr/local/bin/qmake-qt4 -o Makefile qct08.pro
#############################################################################

####### Compiler, tools and options

CC            = clang
CXX           = clang++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -pthread -D_THREAD_SAFE $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -pthread -D_THREAD_SAFE $(DEFINES)
INCPATH       = -I../../../../local/share/qt4/mkspecs/freebsd-clang -I. -I../../../../local/include/qt4/QtCore -I../../../../local/include/qt4/QtNetwork -I../../../../local/include/qt4/QtGui -I../../../../local/include/qt4 -I. -I. -I../../../../local/include/qt4 -I../../../../local/include
LINK          = clang++
LFLAGS        = -Wl,-O1 -pthread -Wl,-rpath,/usr/local/lib/qt4
LIBS          = $(SUBLIBS)  -L/usr/local/lib/qt4 -L/usr/local/lib -lQtGui -L/usr/local/lib -L/usr/local/lib/qt4 -lQtNetwork -lQtCore 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/local/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = Body.cpp \
		ct08.cpp \
		ct08Msg.cpp \
		main.cpp \
		MsgType.cpp \
		ReadConfig.cpp \
		SMsg.cpp \
		Stars.cpp \
		Translator.cpp moc_Body.cpp \
		moc_ct08.cpp \
		moc_Stars.cpp \
		qrc_qct08.cpp
OBJECTS       = Body.o \
		ct08.o \
		ct08Msg.o \
		main.o \
		MsgType.o \
		ReadConfig.o \
		SMsg.o \
		Stars.o \
		Translator.o \
		moc_Body.o \
		moc_ct08.o \
		moc_Stars.o \
		qrc_qct08.o
DIST          = ../../../../local/share/qt4/mkspecs/common/unix.conf \
		../../../../local/share/qt4/mkspecs/common/freebsd.conf \
		../../../../local/share/qt4/mkspecs/common/gcc-base.conf \
		../../../../local/share/qt4/mkspecs/common/gcc-base-unix.conf \
		../../../../local/share/qt4/mkspecs/common/clang.conf \
		../../../../local/share/qt4/mkspecs/common/clang-unix.conf \
		../../../../local/share/qt4/mkspecs/qconfig.pri \
		../../../../local/share/qt4/mkspecs/modules/qt_phonon.pri \
		../../../../local/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		../../../../local/share/qt4/mkspecs/features/qt_functions.prf \
		../../../../local/share/qt4/mkspecs/features/qt_config.prf \
		../../../../local/share/qt4/mkspecs/features/exclusive_builds.prf \
		../../../../local/share/qt4/mkspecs/features/default_pre.prf \
		../../../../local/share/qt4/mkspecs/features/release.prf \
		../../../../local/share/qt4/mkspecs/features/default_post.prf \
		../../../../local/share/qt4/mkspecs/features/shared.prf \
		../../../../local/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		../../../../local/share/qt4/mkspecs/features/warn_on.prf \
		../../../../local/share/qt4/mkspecs/features/qt.prf \
		../../../../local/share/qt4/mkspecs/features/unix/thread.prf \
		../../../../local/share/qt4/mkspecs/features/moc.prf \
		../../../../local/share/qt4/mkspecs/features/resources.prf \
		../../../../local/share/qt4/mkspecs/features/uic.prf \
		../../../../local/share/qt4/mkspecs/features/yacc.prf \
		../../../../local/share/qt4/mkspecs/features/lex.prf \
		../../../../local/share/qt4/mkspecs/features/include_source_dir.prf \
		qct08.pro
QMAKE_TARGET  = qct08
DESTDIR       = 
TARGET        = qct08

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: qct08.pro  ../../../../local/share/qt4/mkspecs/freebsd-clang/qmake.conf ../../../../local/share/qt4/mkspecs/common/unix.conf \
		../../../../local/share/qt4/mkspecs/common/freebsd.conf \
		../../../../local/share/qt4/mkspecs/common/gcc-base.conf \
		../../../../local/share/qt4/mkspecs/common/gcc-base-unix.conf \
		../../../../local/share/qt4/mkspecs/common/clang.conf \
		../../../../local/share/qt4/mkspecs/common/clang-unix.conf \
		../../../../local/share/qt4/mkspecs/qconfig.pri \
		../../../../local/share/qt4/mkspecs/modules/qt_phonon.pri \
		../../../../local/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		../../../../local/share/qt4/mkspecs/features/qt_functions.prf \
		../../../../local/share/qt4/mkspecs/features/qt_config.prf \
		../../../../local/share/qt4/mkspecs/features/exclusive_builds.prf \
		../../../../local/share/qt4/mkspecs/features/default_pre.prf \
		../../../../local/share/qt4/mkspecs/features/release.prf \
		../../../../local/share/qt4/mkspecs/features/default_post.prf \
		../../../../local/share/qt4/mkspecs/features/shared.prf \
		../../../../local/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		../../../../local/share/qt4/mkspecs/features/warn_on.prf \
		../../../../local/share/qt4/mkspecs/features/qt.prf \
		../../../../local/share/qt4/mkspecs/features/unix/thread.prf \
		../../../../local/share/qt4/mkspecs/features/moc.prf \
		../../../../local/share/qt4/mkspecs/features/resources.prf \
		../../../../local/share/qt4/mkspecs/features/uic.prf \
		../../../../local/share/qt4/mkspecs/features/yacc.prf \
		../../../../local/share/qt4/mkspecs/features/lex.prf \
		../../../../local/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/local/lib/qt4/libQtGui.prl \
		/usr/local/lib/qt4/libQtCore.prl \
		/usr/local/lib/qt4/libQtNetwork.prl
	$(QMAKE) -o Makefile qct08.pro
../../../../local/share/qt4/mkspecs/common/unix.conf:
../../../../local/share/qt4/mkspecs/common/freebsd.conf:
../../../../local/share/qt4/mkspecs/common/gcc-base.conf:
../../../../local/share/qt4/mkspecs/common/gcc-base-unix.conf:
../../../../local/share/qt4/mkspecs/common/clang.conf:
../../../../local/share/qt4/mkspecs/common/clang-unix.conf:
../../../../local/share/qt4/mkspecs/qconfig.pri:
../../../../local/share/qt4/mkspecs/modules/qt_phonon.pri:
../../../../local/share/qt4/mkspecs/modules/qt_webkit_version.pri:
../../../../local/share/qt4/mkspecs/features/qt_functions.prf:
../../../../local/share/qt4/mkspecs/features/qt_config.prf:
../../../../local/share/qt4/mkspecs/features/exclusive_builds.prf:
../../../../local/share/qt4/mkspecs/features/default_pre.prf:
../../../../local/share/qt4/mkspecs/features/release.prf:
../../../../local/share/qt4/mkspecs/features/default_post.prf:
../../../../local/share/qt4/mkspecs/features/shared.prf:
../../../../local/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
../../../../local/share/qt4/mkspecs/features/warn_on.prf:
../../../../local/share/qt4/mkspecs/features/qt.prf:
../../../../local/share/qt4/mkspecs/features/unix/thread.prf:
../../../../local/share/qt4/mkspecs/features/moc.prf:
../../../../local/share/qt4/mkspecs/features/resources.prf:
../../../../local/share/qt4/mkspecs/features/uic.prf:
../../../../local/share/qt4/mkspecs/features/yacc.prf:
../../../../local/share/qt4/mkspecs/features/lex.prf:
../../../../local/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/local/lib/qt4/libQtGui.prl:
/usr/local/lib/qt4/libQtCore.prl:
/usr/local/lib/qt4/libQtNetwork.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile qct08.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/qct081.0.0 || $(MKDIR) .tmp/qct081.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/qct081.0.0/ && $(COPY_FILE) --parents Body.h ct08.h ct08Msg.h gitlog.h main.h MsgType.h SMsg.h Stars.h .tmp/qct081.0.0/ && $(COPY_FILE) --parents qct08.qrc .tmp/qct081.0.0/ && $(COPY_FILE) --parents Body.cpp ct08.cpp ct08Msg.cpp main.cpp MsgType.cpp ReadConfig.cpp SMsg.cpp Stars.cpp Translator.cpp .tmp/qct081.0.0/ && (cd `dirname .tmp/qct081.0.0` && $(TAR) qct081.0.0.tar qct081.0.0 && $(COMPRESS) qct081.0.0.tar) && $(MOVE) `dirname .tmp/qct081.0.0`/qct081.0.0.tar.gz . && $(DEL_FILE) -r .tmp/qct081.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_Body.cpp moc_ct08.cpp moc_Stars.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_Body.cpp moc_ct08.cpp moc_Stars.cpp
moc_Body.cpp: ct08.h \
		MsgType.h \
		SMsg.h \
		ct08Msg.h \
		Stars.h \
		Body.h
	/usr/local/bin/moc-qt4 $(DEFINES) $(INCPATH) Body.h -o moc_Body.cpp

moc_ct08.cpp: MsgType.h \
		SMsg.h \
		ct08Msg.h \
		ct08.h
	/usr/local/bin/moc-qt4 $(DEFINES) $(INCPATH) ct08.h -o moc_ct08.cpp

moc_Stars.cpp: SMsg.h \
		MsgType.h \
		Stars.h
	/usr/local/bin/moc-qt4 $(DEFINES) $(INCPATH) Stars.h -o moc_Stars.cpp

compiler_rcc_make_all: qrc_qct08.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_qct08.cpp
qrc_qct08.cpp: qct08.qrc \
		qct08.key
	/usr/local/bin/rcc -name qct08 qct08.qrc -o qrc_qct08.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean 

####### Compile

Body.o: Body.cpp Body.h \
		ct08.h \
		MsgType.h \
		SMsg.h \
		ct08Msg.h \
		Stars.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Body.o Body.cpp

ct08.o: ct08.cpp ct08.h \
		MsgType.h \
		SMsg.h \
		ct08Msg.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ct08.o ct08.cpp

ct08Msg.o: ct08Msg.cpp ct08Msg.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ct08Msg.o ct08Msg.cpp

main.o: main.cpp main.h \
		Body.h \
		ct08.h \
		MsgType.h \
		SMsg.h \
		ct08Msg.h \
		Stars.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

MsgType.o: MsgType.cpp MsgType.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MsgType.o MsgType.cpp

ReadConfig.o: ReadConfig.cpp Body.h \
		ct08.h \
		MsgType.h \
		SMsg.h \
		ct08Msg.h \
		Stars.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ReadConfig.o ReadConfig.cpp

SMsg.o: SMsg.cpp MsgType.h \
		SMsg.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SMsg.o SMsg.cpp

Stars.o: Stars.cpp Stars.h \
		SMsg.h \
		MsgType.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Stars.o Stars.cpp

Translator.o: Translator.cpp Body.h \
		ct08.h \
		MsgType.h \
		SMsg.h \
		ct08Msg.h \
		Stars.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Translator.o Translator.cpp

moc_Body.o: moc_Body.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Body.o moc_Body.cpp

moc_ct08.o: moc_ct08.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ct08.o moc_ct08.cpp

moc_Stars.o: moc_Stars.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Stars.o moc_Stars.cpp

qrc_qct08.o: qrc_qct08.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_qct08.o qrc_qct08.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

